export const sampleProperties = [
  {
    id: 'prop-1',
    property_name: 'Sunset Ridge',
    market: 'Dallas, TX',
    broker_name: 'JLL',
    units: 220,
    year_built: 1998,
    physical_occupancy_pct: 96,
    noi_actual: 1450000,
    expense_ratio_actual: 41,
    dscr_current: 1.62,
    in_place_annual_upside: 380000,
  },
  {
    id: 'prop-2',
    property_name: 'Harbor Point',
    market: 'Austin, TX',
    broker_name: 'CBRE',
    units: 142,
    year_built: 2007,
    physical_occupancy_pct: 91,
    noi_actual: 980000,
    expense_ratio_actual: 47,
    dscr_current: 1.31,
    in_place_annual_upside: 210000,
  },
  {
    id: 'prop-3',
    property_name: 'River Walk Commons',
    market: 'Dallas, TX',
    broker_name: 'Newmark',
    units: 310,
    year_built: 2016,
    physical_occupancy_pct: 88,
    noi_actual: 1820000,
    expense_ratio_actual: 38,
    dscr_current: 1.84,
    in_place_annual_upside: 520000,
  },
]
